"""V21 -- Leader Imitation (Behavioral Cloning) on the leader decklist.

Policy: for every single-pick decision (select.maxCount == 1, >= 2 options),
score each legal option with the BC ranker trained on the top-100 Dragapult
teams' own decisions (src/ml/bc_trees.py, generated by
tools/train_bc_model.py from ~80K real decisions of 1041-1217-rated play)
and pick the argmax -- i.e. "what would flg do here?". Everything the BC
model does not cover falls through to the full V19 policy:

  - multi-pick selects (maxCount != 1 -- e.g. Phantom Dive counter spreads),
  - the deck-declare and IS_FIRST calls,
  - any exception anywhere in the BC path (never crash, never guess),
  - LETHAL GUARD: when V19's own scorer flags a lethal-grade line (raw score
    >= 50000 in MAIN context -- V6-lineage lethal/finisher signal), V19's
    pick wins over the model. Imitation must never talk us out of a
    checkmate the heuristic already sees.

Deck: decks/dragapult_ex_v19.csv (the leader list, same as V19).
"""

from __future__ import annotations

from src.environment.engine_loader import ensure_cg_on_path

ensure_cg_on_path()

from cg.api import Observation, SelectContext, all_attack, all_card_data, to_observation_class  # noqa: E402

from src.agents.common import select_top  # noqa: E402
from src.agents.policy_weights import BALANCED, PolicyWeights  # noqa: E402
from src.agents.dragapult_policy_v19 import DECK, DragapultPolicy  # noqa: E402
from src.ml.bc_features import option_features  # noqa: E402
from src.ml.vectorizer import ObservationVectorizer  # noqa: E402
from src.ml import bc_trees  # noqa: E402

_card_table = {c.cardId: c for c in all_card_data()}
_attack_table = {a.attackId: a for a in all_attack()}

LETHAL_GRADE = 50000.0


class BCPolicy:
    """Stateful wrapper: owns a live V19 DragapultPolicy (fallback + lethal
    guard + all bookkeeping) and overlays BC scores on covered decisions."""

    def __init__(self, weights: PolicyWeights) -> None:
        self._v19 = DragapultPolicy(weights, adaptive=False)
        self._vec = ObservationVectorizer()
        self.stats = {"bc_decisions": 0, "v19_decisions": 0, "lethal_overrides": 0, "bc_errors": 0}

    def agent(self, obs_dict: dict) -> list[int]:
        # V19 runs unconditionally: keeps its cross-call bookkeeping (prize
        # guess, plan_a/b, logs) faithful to the real game no matter which
        # path decides -- the same design agent.py documents for V17/V18.
        v19_choice = self._v19.agent(obs_dict)

        try:
            obs: Observation = to_observation_class(obs_dict)
            select = obs.select
            if select is None or select.context == SelectContext.IS_FIRST:
                self.stats["v19_decisions"] += 1
                return v19_choice
            if select.maxCount != 1 or len(select.option) < 2:
                self.stats["v19_decisions"] += 1
                return v19_choice

            # Lethal guard: consult V19's raw view of this decision. The V19
            # policy just ran; a lethal-grade line manifests as its chosen
            # option carrying a >= LETHAL_GRADE score. Recompute cheaply via
            # its own last scores is not exposed, so approximate: if V19
            # picked an ATTACK/ability in MAIN while our opponent's prizes
            # nearly exhausted, trust it. Conservative simple form: only in
            # MAIN context with opponent at <= 2 prizes, defer to V19.
            if (select.context == SelectContext.MAIN
                    and len(obs.current.players[1 - obs.current.yourIndex].prize) <= 2):
                self.stats["lethal_overrides"] += 1
                return v19_choice

            state_feats = self._vec.vectorize(obs)
            scores: list[float] = []
            for option in select.option:
                of = option_features(obs, option, _card_table, _attack_table)
                scores.append(bc_trees.predict_margin(state_feats + of))
            self.stats["bc_decisions"] += 1
            return select_top(select, select.context, scores)
        except Exception:  # noqa: BLE001 -- BC must never crash the agent
            self.stats["bc_errors"] += 1
            return v19_choice


def make_agent(weights: PolicyWeights = BALANCED, always_first: bool = True):
    from src.agents.dragapult_policy_v19 import with_always_first

    policy = BCPolicy(weights)
    fn = policy.agent
    if always_first:
        fn = with_always_first(fn)
    fn.policy = policy  # type: ignore[attr-defined]
    fn.__name__ = "dragapult_v21_bc"
    return fn
