"""Exports the trained B1 P(win) model (results/b1/xgb_pwin.json) into a
self-contained C++ header of flat arrays + an iterative evaluator --
src/agents/dragapult_agent_v20_cpp/cpp/pwin_trees.hpp.

Parses xgboost's NATIVE json (exact float32 split thresholds and leaf
values), not get_dump()'s text rendering -- the text path cost ~0.009
probability parity error; this path is exact by construction. xgboost JSON
schema notes (verified against the loaded file, not assumed):
  learner.gradient_booster.model.trees[t] has parallel arrays
  split_indices / split_conditions / left_children / right_children /
  default_left; a node is a leaf iff left_children[i] == -1, and a leaf's
  value lives in split_conditions[i] (the schema reuses that array).
Only trees [0, best_iteration] are exported (early stopping).

Also emits a parity fixture: results/b1/parity_fixture.csv with 200 valid
rows' features + xgboost-predicted P(win), for the C++ side's parity test.

Usage:
    python tools/export_b1_cpp.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

B1_DIR = REPO_ROOT / "results" / "b1"
OUT_HPP = REPO_ROOT / "src" / "agents" / "dragapult_agent_v20_cpp" / "cpp" / "pwin_trees.hpp"


def main() -> None:
    import numpy as np
    import pandas as pd
    import xgboost as xgb

    model = xgb.XGBClassifier()
    model.load_model(B1_DIR / "xgb_pwin.json")
    raw = json.loads(B1_DIR.joinpath("xgb_pwin.json").read_text(encoding="utf-8"))
    learner = raw["learner"]
    trees = learner["gradient_booster"]["model"]["trees"]
    base_score = float(learner["learner_model_param"]["base_score"].strip("[]"))
    best_iteration = int(json.loads(learner["attributes"]["best_iteration"])) if "best_iteration" in learner.get("attributes", {}) else len(trees) - 1
    n_trees = best_iteration + 1
    trees = trees[:n_trees]
    print(f"trees={len(trees)} (best_iteration={best_iteration}), base_score={base_score}")

    # Flatten all trees into single arrays with per-tree offsets.
    feat, thr, left, right = [], [], [], []
    tree_root: list[int] = []
    for t in trees:
        offset = len(feat)
        tree_root.append(offset)
        si = t["split_indices"]
        sc = t["split_conditions"]
        lc = t["left_children"]
        rc = t["right_children"]
        n = len(si)
        for i in range(n):
            is_leaf = lc[i] == -1
            feat.append(-1 if is_leaf else int(si[i]))
            thr.append(float(sc[i]))  # leaf value when is_leaf
            left.append(-1 if is_leaf else offset + int(lc[i]))
            right.append(-1 if is_leaf else offset + int(rc[i]))

    import math
    margin_offset = math.log(base_score / (1.0 - base_score))

    def arr(name: str, vals, ctype: str, fmt) -> str:
        body = ",".join(fmt(v) for v in vals)
        return f"inline constexpr {ctype} {name}[] = {{{body}}};\n"

    hpp = [
        "// GENERATED by tools/export_b1_cpp.py from results/b1/xgb_pwin.json --",
        "// do not edit. B1 learned P(win) evaluator: flat-array XGBoost forest,",
        "// exact float32 splits/leaves from the native model JSON.",
        "#pragma once",
        "#include <cmath>",
        "",
        "namespace v20 {",
        "",
        f"inline constexpr int kPwinNumTrees = {len(tree_root)};",
        f"inline constexpr double kPwinMarginOffset = {margin_offset!r};",
        f"inline constexpr int kPwinFeatureCount = 87;",
        "",
        arr("kPwinTreeRoot", tree_root, "int", lambda v: str(v)),
        arr("kPwinFeat", feat, "int", lambda v: str(v)),
        arr("kPwinThr", thr, "float", lambda v: f"{v!r}f"),
        arr("kPwinLeft", left, "int", lambda v: str(v)),
        arr("kPwinRight", right, "int", lambda v: str(v)),
        "// Returns P(the acting player of this feature vector wins).",
        "inline double pwin_predict(const float* x) {",
        "  double s = kPwinMarginOffset;",
        "  for (int t = 0; t < kPwinNumTrees; ++t) {",
        "    int node = kPwinTreeRoot[t];",
        "    while (kPwinFeat[node] >= 0) {",
        "      node = (x[kPwinFeat[node]] < kPwinThr[node]) ? kPwinLeft[node] : kPwinRight[node];",
        "    }",
        "    s += kPwinThr[node];",
        "  }",
        "  return 1.0 / (1.0 + std::exp(-s));",
        "}",
        "",
        "}  // namespace v20",
    ]
    OUT_HPP.parent.mkdir(parents=True, exist_ok=True)
    OUT_HPP.write_text("\n".join(hpp), encoding="utf-8")
    print(f"Wrote {OUT_HPP} ({OUT_HPP.stat().st_size / 1e6:.1f} MB)")

    # Parity fixture: 200 rows features + reference predictions.
    df = pd.read_parquet(B1_DIR / "dataset.parquet")
    feat_cols = [c for c in df.columns if c.startswith("f")]
    sample = df.sample(200, random_state=7)
    ref = model.predict_proba(sample[feat_cols])[:, 1]
    fixture = sample[feat_cols].copy()
    fixture["ref_pwin"] = ref
    fixture.to_csv(B1_DIR / "parity_fixture.csv", index=False)

    # Python-side sanity: evaluate the exported arrays in pure Python on the
    # fixture and compare (catches schema misreads before C++ ever compiles).
    feat_np = np.array(feat)
    # float32, NOT float64: xgboost compares feature vs threshold in float32;
    # a float64 comparison flips borderline splits (hit for real on 3/200
    # fixture rows via NEP-50 promotion). The generated C++ header already
    # compares float vs float -- this keeps the Python check semantics equal.
    thr_np = np.array(thr, dtype=np.float32)
    left_np = np.array(left)
    right_np = np.array(right)

    def predict_row(x):
        s = margin_offset
        for root in tree_root:
            node = root
            while feat_np[node] >= 0:
                node = left_np[node] if x[feat_np[node]] < thr_np[node] else right_np[node]
            s += thr_np[node]
        return 1.0 / (1.0 + np.exp(-s))

    X = sample[feat_cols].to_numpy(dtype=np.float32)
    ours = np.array([predict_row(x) for x in X])
    errs = np.abs(ours - ref)
    wi = int(np.argmax(errs))
    xw = X[wi]
    s_flat = margin_offset
    for root in tree_root:
        node = root
        while feat[node] >= 0:
            node = left[node] if xw[feat[node]] < thr[node] else right[node]
        s_flat += thr[node]
    s_direct = margin_offset
    for t in trees:
        si, sc, lc, rc = t["split_indices"], t["split_conditions"], t["left_children"], t["right_children"]
        n = 0
        while lc[n] != -1:
            n = lc[n] if xw[si[n]] < sc[n] else rc[n]
        s_direct += sc[n]
    import xgboost as _xgb
    ref_margin = model.get_booster().predict(_xgb.DMatrix(sample[feat_cols].iloc[[wi]]),
                                             output_margin=True)[0]
    print(f"DEBUG worst row {wi}: s_flat={s_flat:.6f} s_direct={s_direct:.6f} ref_margin={ref_margin:.6f}")
    max_err = float(np.max(errs))
    print(f"array-export parity vs xgboost (200 rows): max_err={max_err:.2e}, "
          f"rows>1e-4: {(errs > 1e-4).sum()}, worst_idx={int(np.argmax(errs))}, "
          f"ours={ours[int(np.argmax(errs))]:.4f} ref={ref[int(np.argmax(errs))]:.4f}")
    if max_err > 1e-5:
        raise SystemExit("PARITY FAIL: array export does not reproduce xgboost -- do not ship")


if __name__ == "__main__":
    main()
