"""Exports the leader-imitation BC ranker (results/b1/xgb_bc.json, 103
features = 87 state + 16 option) into C++ flat arrays for V26's neural
priors -- same exact-native-json/float32 method as tools/export_b1_cpp.py
(incl. its hard-won parity lessons).

Writes src/agents/dragapult_agent_v26_cpp/cpp/bc_trees.hpp and a parity
fixture results/b1/bc_parity_fixture.csv.
"""

from __future__ import annotations

import json
import math
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

B1_DIR = REPO_ROOT / "results" / "b1"
OUT_HPP = REPO_ROOT / "src" / "agents" / "dragapult_agent_v26_cpp" / "cpp" / "bc_trees.hpp"


def main() -> None:
    import numpy as np
    import pandas as pd
    import xgboost as xgb

    model = xgb.XGBClassifier()
    model.load_model(B1_DIR / "xgb_bc.json")
    raw = json.loads((B1_DIR / "xgb_bc.json").read_text(encoding="utf-8"))
    learner = raw["learner"]
    trees = learner["gradient_booster"]["model"]["trees"][: model.best_iteration + 1]
    base_score = float(learner["learner_model_param"]["base_score"].strip("[]"))
    margin_offset = math.log(base_score / (1.0 - base_score))

    feat, thr, left, right, tree_root = [], [], [], [], []
    for t in trees:
        offset = len(feat)
        tree_root.append(offset)
        si, sc, lc, rc = t["split_indices"], t["split_conditions"], t["left_children"], t["right_children"]
        for i in range(len(si)):
            is_leaf = lc[i] == -1
            feat.append(-1 if is_leaf else int(si[i]))
            thr.append(float(sc[i]))
            left.append(-1 if is_leaf else offset + int(lc[i]))
            right.append(-1 if is_leaf else offset + int(rc[i]))

    def arr(name, vals, ctype, fmt):
        return f"inline constexpr {ctype} {name}[] = {{{','.join(fmt(v) for v in vals)}}};\n"

    hpp = [
        "// GENERATED by tools/export_bc_cpp.py from results/b1/xgb_bc.json --",
        "// do not edit. Leader-imitation ranker (V26 neural priors): input is",
        "// 103 floats = the 87 vectorizer.hpp state features + the 16 option",
        "// features (bc_option_features.hpp, ported from src/ml/bc_features.py).",
        "#pragma once", "#include <cmath>", "", "namespace v26 {", "",
        f"inline constexpr int kBcNumTrees = {len(tree_root)};",
        f"inline constexpr double kBcMarginOffset = {margin_offset!r};",
        "inline constexpr int kBcFeatureCount = 103;", "",
        arr("kBcTreeRoot", tree_root, "int", str),
        arr("kBcFeat", feat, "int", str),
        arr("kBcThr", thr, "float", lambda v: f"{v!r}f"),
        arr("kBcLeft", left, "int", str),
        arr("kBcRight", right, "int", str),
        "// Returns the raw margin (logit); higher = more leader-like option.",
        "inline double bc_predict_margin(const float* x) {",
        "  double s = kBcMarginOffset;",
        "  for (int t = 0; t < kBcNumTrees; ++t) {",
        "    int node = kBcTreeRoot[t];",
        "    while (kBcFeat[node] >= 0) {",
        "      node = (x[kBcFeat[node]] < kBcThr[node]) ? kBcLeft[node] : kBcRight[node];",
        "    }",
        "    s += kBcThr[node];",
        "  }",
        "  return s;",
        "}",
        "", "}  // namespace v26",
    ]
    OUT_HPP.write_text("\n".join(hpp), encoding="utf-8")
    print(f"Wrote {OUT_HPP} ({OUT_HPP.stat().st_size / 1e6:.1f} MB, trees={len(tree_root)})")

    # Parity check with float32 semantics on real BC rows.
    df = pd.read_parquet(B1_DIR / "bc_dataset.parquet")
    feat_cols = [c for c in df.columns if (c[0] in "so") and c[1:].isdigit()]
    assert len(feat_cols) == 103, len(feat_cols)
    sample = df.sample(300, random_state=7)[feat_cols]
    ref = model.predict_proba(sample)[:, 1]
    X32 = sample.to_numpy(dtype=np.float32)
    feat_np = np.array(feat)
    thr32 = np.array(thr, dtype=np.float32)
    left_np, right_np = np.array(left), np.array(right)

    def margin(x):
        s = margin_offset
        for root in tree_root:
            n = root
            while feat_np[n] >= 0:
                n = left_np[n] if x[feat_np[n]] < thr32[n] else right_np[n]
            s += thr32[n]
        return s

    ours = 1.0 / (1.0 + np.exp(-np.array([margin(x) for x in X32])))
    max_err = float(np.max(np.abs(ours - ref)))
    print(f"parity (300 rows): {max_err:.2e}")
    if max_err > 1e-5:
        raise SystemExit("PARITY FAIL")


if __name__ == "__main__":
    main()
