"""Generates src/agents/dragapult_agent_v18_cpp/archetype_decks.py -- the
embedded canonical decklists V18's opponent-archetype determinization (Block
A1) classifies against and samples hidden zones from.

Why embedded as a generated Python module rather than read from decks/*.csv at
runtime: the Kaggle submission archive must be self-contained with no
path-relative data dependencies (main.py runs from /kaggle_simulations/agent
with its own cwd rules); a generated constant module ships inside the agent
package itself and cannot go missing or resolve to the wrong path.

Sources (replay-derived canonical lists where one exists -- see
reports/real_meta_v2.md / results/meta/archetype_canonical.csv lineage -- and
the local sample decks as variants of the same families):
    decks/meta_*.csv          real-ladder canonical archetype lists (by ID)
    decks/dragapult_ex.csv    OUR OWN deck (the V6/V17/V18 mirror), kept as a
                              Dragapult-family variant so a true mirror
                              opponent matches it exactly
    decks/*.csv (local)       local sample decks for families with no meta_*
                              list (Abomasnow, Iono's) or as extra variants

Re-run after any decks/ change:
    python tools/gen_v18_archetype_decks.py
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from src.agents.common import load_deck_csv  # noqa: E402

DECKS_DIR = REPO_ROOT / "decks"
OUT_PATH = REPO_ROOT / "src" / "agents" / "dragapult_agent_v18_cpp" / "archetype_decks.py"

# (family, variant label, deck csv). Family is the archetype identity used for
# the classification margin rule (variants of one family never compete against
# each other); variant is diagnostic only.
SOURCES = [
    ("Marnie's Grimmsnarl ex", "meta_canonical", "meta_marnie_s_grimmsnarl_ex.csv"),
    ("Fezandipiti ex", "meta_canonical", "meta_fezandipiti_ex.csv"),
    ("Mega Kangaskhan ex", "meta_canonical", "meta_mega_kangaskhan_ex.csv"),
    ("Team Rocket's Mewtwo ex", "meta_canonical", "meta_team_rocket_s_mewtwo_ex.csv"),
    ("Team Rocket's Mewtwo ex", "local_sample", "team_rockets_mewtwo_ex.csv"),
    ("Cynthia's Garchomp ex", "meta_canonical", "meta_cynthia_s_garchomp_ex.csv"),
    ("Dragapult ex", "meta_canonical", "meta_dragapult_ex.csv"),
    ("Dragapult ex", "our_v6_mirror", "dragapult_ex.csv"),
    ("Dragapult ex", "our_v10_variant", "dragapult_ex_v10.csv"),
    ("Dragapult ex", "our_v13_turbo", "dragapult_v13_turbo.csv"),
    ("Mega Lopunny ex", "meta_canonical", "meta_mega_lopunny_ex.csv"),
    ("Mega Lucario ex", "meta_canonical", "meta_mega_lucario_ex.csv"),
    ("Mega Lucario ex", "local_sample", "lucario_ex.csv"),
    ("Teal Mask Ogerpon ex", "meta_canonical", "meta_teal_mask_ogerpon_ex.csv"),
    ("Abra/Alakazam cluster", "meta_canonical", "meta_unlabeled_cluster01_abra_alakazam.csv"),
    ("Mega Abomasnow ex", "local_sample", "abomasnow_ex_corrected_v1.csv"),
    ("Iono's (Bellibolt/Voltorb)", "local_sample", "iono.csv"),
]


def main() -> None:
    entries = []
    for family, variant, filename in SOURCES:
        path = DECKS_DIR / filename
        deck = load_deck_csv(path)
        if len(deck) != 60:
            raise SystemExit(f"{filename}: expected 60 cards, got {len(deck)}")
        entries.append((family, variant, filename, sorted(deck)))

    lines = [
        '"""GENERATED by tools/gen_v18_archetype_decks.py -- do not edit by hand.',
        "",
        "Canonical archetype decklists (60 card IDs each) for V18's Block-A1",
        "opponent-archetype determinization. See the generator's docstring for",
        'sources and regeneration instructions."""',
        "",
        "# (family, variant, source_file, 60 sorted card ids)",
        "ARCHETYPE_DECKS: list[tuple[str, str, str, list[int]]] = [",
    ]
    for family, variant, filename, deck in entries:
        lines.append(f"    ({family!r}, {variant!r}, {filename!r},")
        lines.append(f"     {deck!r}),")
    lines.append("]")
    lines.append("")
    OUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT_PATH} ({len(entries)} decks, "
          f"{len(set(f for f, _, _, _ in entries))} families)")


if __name__ == "__main__":
    main()
