"""Packages the V17 native C++ MCTS source into a single, paste-ready Kaggle
notebook cell so compilation can be tested on Kaggle's actual grading
container instead of guessed at locally.

Why this exists: this dev machine has MSVC (via VS Build Tools), not g++, so
nothing built here proves the g++/Linux/GLIBC combination Kaggle's grading
container actually has (see src/agents/dragapult_agent_v17_cpp/compile.sh's
own comment). The only way to find out is to run the real compile command on
Kaggle itself.

Note on binding style: this library is NOT a pybind11 module. v17_agent.cpp
exports a plain `extern "C"` ABI (v17_init / v17_choose_action, see
cpp/v17_abi.h) that native_bridge.py loads with ctypes.CDLL, not
`import <module>`. The generated cell mirrors that reality: it compiles with
the exact g++ invocation compile.sh/native_bridge.py already use (plus -Wall,
as requested, for extra warning visibility), then verifies the result the
ctypes way -- CDLL-loading the .so and resolving both exported symbols. A
CDLL load fails immediately on the same class of problem `import` would (
missing symbols, GLIBC version mismatches), so it's the correct equivalent
check for this ABI, not a gap.

Usage:
    python tools/make_kaggle_test_cell.py

Writes kaggle_notebook_cell.py at the repo root. Paste its contents into a
single Kaggle notebook cell and run it there.
"""

from __future__ import annotations

from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent

# Which agent package to bundle: "v18" (default -- current) or "v17". V18's
# package adds generic_opponent.hpp (Block A1.5) to the include closure; the
# exported C symbols are unchanged (still v17_init/v17_choose_action -- only
# the ABI struct/magic changed, which a compile+load check doesn't exercise).
import sys as _sys

_VERSION = _sys.argv[1] if len(_sys.argv) > 1 else "v18"
_CPP_DIR = _REPO_ROOT / "src" / "agents" / f"dragapult_agent_{_VERSION}_cpp" / "cpp"
_OUTPUT_FILE = _REPO_ROOT / (
    "kaggle_notebook_cell.py" if _VERSION == "v17" else f"kaggle_notebook_cell_{_VERSION}.py"
)

# v17_agent.cpp is the single translation unit; these are its full transitive
# #include closure (verified by grepping every `#include "..."` in the cpp/
# dir) -- everything g++ needs to see to reproduce the real build.
_SOURCE_FILE = "v17_agent.cpp"
_HEADER_FILES = [
    "v17_abi.h",
    "json_extract.hpp",
    "card_data.hpp",
    "cg_engine.hpp",
    "deck_tracking.hpp",
    "observation.hpp",
    "v6_heuristic.hpp",
    "v6_heuristic_scores.hpp",
    "mcts.hpp",
]
if _VERSION != "v17":
    _HEADER_FILES.append("generic_opponent.hpp")
if _VERSION in ("v20", "v22", "v23", "v24", "v25", "v26"):
    _HEADER_FILES += ["pwin_trees.hpp", "vectorizer.hpp"]
if _VERSION in ("v24", "v25", "v26"):
    _HEADER_FILES.append("tree_search.hpp")
if _VERSION == "v26":
    _HEADER_FILES += ["bc_trees.hpp", "bc_option_features.hpp"]

_LIB_NAME = f"{_VERSION}_mcts.so"

# Exact command from compile.sh / native_bridge.py's _compile_with_gxx Linux
# path, with -Wall added for extra warning visibility on Kaggle's compiler.
_COMPILE_ARGS = [
    "g++", "-O3", "-Wall", "-shared", "-fPIC", "-std=c++17",
    "-o", _LIB_NAME, _SOURCE_FILE, "-ldl",
]

_EXPORTED_SYMBOLS = ["v17_init", "v17_choose_action"]


def _read_sources() -> dict[str, str]:
    sources: dict[str, str] = {}
    for name in [_SOURCE_FILE, *_HEADER_FILES]:
        path = _CPP_DIR / name
        if not path.exists():
            raise FileNotFoundError(f"Expected C++ source not found: {path}")
        sources[name] = path.read_text(encoding="utf-8")
    return sources


def _render_cell(sources: dict[str, str]) -> str:
    file_writes = "\n".join(
        f"write_source({name!r}, {content!r})" for name, content in sources.items()
    )

    return f'''"""Kaggle notebook cell -- generated by tools/make_kaggle_test_cell.py.

Do not hand-edit: regenerate from the repo instead so this stays in sync with
src/agents/dragapult_agent_v17_cpp/cpp/. Paste this whole cell into a Kaggle
notebook and run it. It writes the V17 native C++ sources into the working
directory, compiles them with the exact command the real submission uses on
Linux (see ../compile.sh / native_bridge.py's _compile_with_gxx), and then
CDLL-loads the result to catch ABI/GLIBC linking problems -- this library
exports a plain extern "C" ABI loaded via ctypes (see cpp/v17_abi.h /
native_bridge.py), not a pybind11 module, so a ctypes.CDLL load + symbol
resolution is the correct equivalent of "import the module and see if it
blows up" for this binding style.
"""

import ctypes
import subprocess
import sys
from pathlib import Path

WORK_DIR = Path("/kaggle/working/{_VERSION}_cpp_test")
WORK_DIR.mkdir(parents=True, exist_ok=True)


def write_source(filename: str, content: str) -> None:
    with open(WORK_DIR / filename, "w", encoding="utf-8") as f:
        f.write(content)


{file_writes}

print(f"Wrote {len(sources)} source files to {{WORK_DIR}}")

compile_cmd = {_COMPILE_ARGS!r}
print("Compiling:", " ".join(compile_cmd))
result = subprocess.run(
    compile_cmd,
    cwd=str(WORK_DIR),
    capture_output=True,
    text=True,
    timeout=300,
)
print("--- g++ stdout ---")
print(result.stdout)
print("--- g++ stderr (includes -Wall warnings) ---")
print(result.stderr)

if result.returncode != 0:
    print(f"COMPILE FAILED (exit code {{result.returncode}})")
    sys.exit(1)

lib_path = WORK_DIR / {_LIB_NAME!r}
if not lib_path.exists():
    print(f"COMPILE reported success but {{lib_path}} is missing")
    sys.exit(1)

print(f"Compiled OK: {{lib_path}} ({{lib_path.stat().st_size}} bytes)")

# Equivalent of "import the compiled module" for a ctypes-loaded extern "C"
# .so: CDLL() itself performs dynamic linking/symbol resolution against the
# running container's loader and libc, so it fails immediately on the same
# ABI/GLIBC problems an `import compiled_module.so` would surface for a
# pybind11 module.
try:
    lib = ctypes.CDLL(str(lib_path))
    print(f"ctypes.CDLL load OK: {{lib}}")
except OSError as exc:
    print(f"ctypes.CDLL LOAD FAILED (ABI/GLIBC linking error): {{exc!r}}")
    sys.exit(1)

missing = []
for symbol in {_EXPORTED_SYMBOLS!r}:
    try:
        getattr(lib, symbol)
        print(f"Symbol resolved OK: {{symbol}}")
    except AttributeError as exc:
        print(f"MISSING SYMBOL: {{symbol}} ({{exc!r}})")
        missing.append(symbol)

if missing:
    print(f"FAILED: {{len(missing)}} expected symbol(s) not found in {{lib_path.name}}")
    sys.exit(1)

print("SUCCESS: {_LIB_NAME} compiled and loaded cleanly on this container.")
'''


def main() -> None:
    sources = _read_sources()
    cell_code = _render_cell(sources)
    _OUTPUT_FILE.write_text(cell_code, encoding="utf-8")
    print(f"Read {len(sources)} source files from {_CPP_DIR}")
    print(f"Wrote {_OUTPUT_FILE} ({_OUTPUT_FILE.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
