"""V21/BC training: imitate leader option choices.

Binary XGBoost over (state, option) rows from results/b1/bc_dataset.parquet
(label: leader picked this option). EPISODE-level train/valid split (same
leakage discipline as B1). The metric that matters is GROUPED top-1
accuracy: within each real decision (episode, step, player), does the
model's argmax equal the leader's actual pick? Reported overall, by option
count, and by turn bucket; baseline = always-pick-option-0 and random.

Outputs:
  results/b1/xgb_bc.json      -- native model
  results/b1/bc_trees.py      -- dependency-free export (float32 semantics,
                                 same validated pattern as B1's pwin export)
  results/b1/bc_report.md     -- metrics
"""

from __future__ import annotations

import json
import math
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

OUT_DIR = REPO_ROOT / "results" / "b1"


def main() -> None:
    import numpy as np
    import pandas as pd
    import xgboost as xgb
    from sklearn.metrics import roc_auc_score

    df = pd.read_parquet(OUT_DIR / "bc_dataset.parquet")
    feat_cols = [c for c in df.columns if c.startswith("s") and c[1:].isdigit()] + \
                [c for c in df.columns if c.startswith("o") and c[1:].isdigit()]
    df["group"] = df["episode_id"].astype(str) + "/" + df["step"].astype(str) + "/" + df["player"].astype(str)
    print(f"rows={len(df)} decisions={df['group'].nunique()} episodes={df['episode_id'].nunique()} "
          f"features={len(feat_cols)} chosen_rate={df['chosen'].mean():.3f}")

    rng = np.random.default_rng(42)
    episodes = np.array([str(e) for e in df["episode_id"].unique()])
    rng.shuffle(episodes)
    n_valid = max(1, int(len(episodes) * 0.2))
    valid_eps = set(episodes[:n_valid])
    is_valid = df["episode_id"].astype(str).isin(valid_eps)
    tr, va = df[~is_valid], df[is_valid]
    print(f"train {len(tr)} rows / valid {len(va)} rows ({n_valid} episodes)")

    model = xgb.XGBClassifier(
        n_estimators=500, max_depth=7, learning_rate=0.1,
        subsample=0.8, colsample_bytree=0.8, min_child_weight=10,
        eval_metric="logloss", early_stopping_rounds=30, n_jobs=4,
    )
    model.fit(tr[feat_cols], tr["chosen"], eval_set=[(va[feat_cols], va["chosen"])], verbose=100)

    p = model.predict_proba(va[feat_cols])[:, 1]
    va2 = va[["group", "option_i", "chosen", "turn" if "turn" in va.columns else "s0"]].copy()
    va2["p"] = p
    # grouped top-1: model argmax == leader pick
    top1 = 0
    first_opt = 0
    rand_sum = 0.0
    groups = 0
    for _, g in va2.groupby("group", sort=False):
        groups += 1
        pick = g.loc[g["p"].idxmax(), "chosen"]
        top1 += int(pick == 1)
        first_opt += int(g.iloc[0]["chosen"] == 1)
        rand_sum += 1.0 / len(g)
    auc = roc_auc_score(va["chosen"], p)
    lines = ["# BC (leader imitation) training report", "",
             f"rows={len(df)}, decisions={df['group'].nunique()}, features={len(feat_cols)}",
             f"valid AUC(rowwise)={auc:.4f}, best_iteration={model.best_iteration}",
             f"GROUPED top-1 accuracy: {top1 / groups:.4f} (n={groups} decisions)",
             f"baselines: first-option {first_opt / groups:.4f}, random {rand_sum / groups:.4f}", ""]

    model.save_model(OUT_DIR / "xgb_bc.json")

    # Dependency-free export, float32 comparison semantics (B1's hard-won
    # lesson: xgboost compares in float32; float64 promotion flips borderline
    # splits -- see tools/export_b1_cpp.py).
    raw = json.loads((OUT_DIR / "xgb_bc.json").read_text(encoding="utf-8"))
    learner = raw["learner"]
    trees = learner["gradient_booster"]["model"]["trees"][: model.best_iteration + 1]
    base_score = float(learner["learner_model_param"]["base_score"].strip("[]"))
    margin_offset = math.log(base_score / (1.0 - base_score))
    feat, thr, left, right, tree_root = [], [], [], [], []
    for t in trees:
        offset = len(feat)
        tree_root.append(offset)
        si, sc, lc, rc = t["split_indices"], t["split_conditions"], t["left_children"], t["right_children"]
        for i in range(len(si)):
            is_leaf = lc[i] == -1
            feat.append(-1 if is_leaf else int(si[i]))
            thr.append(float(np.float32(sc[i])))
            left.append(-1 if is_leaf else offset + int(lc[i]))
            right.append(-1 if is_leaf else offset + int(rc[i]))
    code = [
        '"""GENERATED by tools/train_bc_model.py -- do not edit. Leader-imitation',
        'ranker forest. predict_margin(x) scores one (state87+option16) feature',
        'row; higher = more leader-like. Comparisons MUST stay float32."""',
        "import math",
        "import struct",
        "",
        f"MARGIN_OFFSET = {margin_offset!r}",
        f"TREE_ROOT = {tree_root!r}",
        f"FEAT = {feat!r}",
        f"THR = {thr!r}",
        f"LEFT = {left!r}",
        f"RIGHT = {right!r}",
        "",
        "def _f32(v):",
        "    return struct.unpack('f', struct.pack('f', v))[0]",
        "",
        "THR_F32 = [_f32(t) for t in THR]",
        "",
        "def predict_margin(x):",
        "    x32 = [_f32(v) for v in x]",
        "    s = MARGIN_OFFSET",
        "    for root in TREE_ROOT:",
        "        n = root",
        "        while FEAT[n] >= 0:",
        "            n = LEFT[n] if x32[FEAT[n]] < THR_F32[n] else RIGHT[n]",
        "        s += THR_F32[n]",
        "    return s",
        "",
        "def predict_proba(x):",
        "    return 1.0 / (1.0 + math.exp(-predict_margin(x)))",
    ]
    (OUT_DIR / "bc_trees.py").write_text("\n".join(code), encoding="utf-8")

    # Parity check vs xgboost on 300 valid rows.
    ns: dict = {}
    exec((OUT_DIR / "bc_trees.py").read_text(encoding="utf-8"), ns)
    sample = va[feat_cols].head(300)
    ref = model.predict_proba(sample)[:, 1]
    X32 = sample.to_numpy(dtype=np.float32)
    ours = np.array([ns["predict_proba"](row.tolist()) for row in X32])
    max_err = float(np.max(np.abs(ours - ref)))
    lines.append(f"export parity (300 rows): max_err={max_err:.2e}")
    print(f"export parity max_err={max_err:.2e}")
    if max_err > 1e-5:
        raise SystemExit("PARITY FAIL -- do not ship")

    (OUT_DIR / "bc_report.md").write_text("\n".join(lines), encoding="utf-8")
    print("\n".join(lines[:8]))


if __name__ == "__main__":
    main()
